In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
import numpy as np
import csv
import collections

tfidf_pca = np.loadtxt('/home/eshaw/Documents/NLP/eshaw2-finalproject/dream_pca_tf-idf.txt')
verbs_matrix = np.loadtxt('/home/eshaw/Documents/NLP/eshaw2-finalproject/dream_verb_types.txt')
attr_matrix = np.loadtxt('/home/eshaw/Documents/NLP/eshaw2-finalproject/dream_mod_types.txt')

In [60]:
tfidf_pca

array([[-0.2668813 ,  0.23704371, -0.12596208,  0.10937757],
       [-0.10074654, -0.1796325 , -0.05940608,  0.24922056],
       [ 0.28804449,  0.57484135, -0.1010682 , -0.3367975 ],
       [-0.2090799 , -0.18882833,  0.06255186,  0.07054171],
       [ 0.47452416, -0.26763671, -0.60866496,  0.03600406],
       [-0.04822122, -0.26502113,  0.0810346 , -0.19064134],
       [ 0.0842244 , -0.30288507,  0.20000201, -0.57257343],
       [ 0.12039329, -0.29172272, -0.09061794,  0.24888083],
       [ 0.28351953,  0.32031843,  0.18580395,  0.20533113],
       [ 0.29456971, -0.00116068,  0.30382156,  0.27362463],
       [-0.27062935, -0.02508904,  0.1485846 , -0.1137965 ],
       [-0.25954165, -0.06663478,  0.16239175, -0.11299767],
       [ 0.50830854,  0.07808535,  0.44036774,  0.12801747],
       [-0.27012258,  0.0982329 , -0.11011663,  0.18207582],
       [ 0.24975345, -0.14405981, -0.27386199, -0.12355515],
       [-0.11483753,  0.3467783 , -0.18405007, -0.2245188 ],
       [-0.29873318,  0.

In [14]:
print np.shape(tfidf_pca)
print np.shape(verbs_matrix)
print np.shape(attr_matrix)

(19, 4)
(19, 2)
(19, 2)


In [15]:
info_matrix = np.concatenate((tfidf_pca, verbs_matrix, attr_matrix), axis=1)
print np.shape(info_matrix)

In [36]:
cosine_similarities = cosine_similarity(info_matrix)
cosine_similarities

array([[ 1.        ,  0.98819387,  0.97514404,  0.92412773,  0.98750012,
         0.99548939,  0.98124924,  0.97335226,  0.96759657,  0.95591946,
         0.98303665,  0.95345711,  0.98066207,  0.94731223,  0.96909569,
         0.98290509,  0.99237642,  0.9780255 ,  0.98228418],
       [ 0.98819387,  1.        ,  0.99214737,  0.96192858,  0.98779112,
         0.99720096,  0.9598826 ,  0.99197965,  0.93613043,  0.97696484,
         0.98410049,  0.98027571,  0.98224859,  0.98127877,  0.98275728,
         0.99613555,  0.99895766,  0.9977572 ,  0.98341262],
       [ 0.97514404,  0.99214737,  1.        ,  0.93864074,  0.99130667,
         0.98919553,  0.93230026,  0.99317917,  0.89910001,  0.99573107,
         0.95508655,  0.9814004 ,  0.99129434,  0.98860968,  0.96290613,
         0.98597665,  0.98661577,  0.99160785,  0.99111337],
       [ 0.92412773,  0.96192858,  0.93864074,  1.        ,  0.9243345 ,
         0.94808404,  0.89005907,  0.96175956,  0.86847329,  0.9166898 ,
         0.959

In [38]:
verbs_matrix = np.loadtxt('/home/eshaw/Documents/NLP/eshaw2-finalproject/dream_verb_types.txt')
attr_matrix = np.loadtxt('/home/eshaw/Documents/NLP/eshaw2-finalproject/dream_mod_types.txt')

In [45]:
from scipy import stats

agent = stats.zscore(verbs_matrix[:,0])
patient = stats.zscore(verbs_matrix[:,1])
attr = stats.zscore(attr_matrix[:,0])
mod = stats.zscore(attr_matrix[:,1])

In [49]:
print np.shape(agent)
print np.shape(patient)
print np.shape(attr)
print np.shape(mod)
print np.shape(tfidf_pca)

(19,)
(19,)
(19,)
(19,)
(19, 4)


In [56]:
grammar_matrix = np.column_stack((agent,patient,attr,mod))

In [57]:
grammar_matrix

array([[ 0.01448109,  0.27323539,  0.81160342,  0.03768979],
       [-0.97602515, -0.94653749, -1.06201714, -0.92629905],
       [ 1.6469821 ,  1.40375659,  1.35665667,  0.61608309],
       [-1.06773869, -1.09529028, -1.220991  , -0.89875651],
       [ 0.89493107,  1.55250938,  1.49291998,  0.94659355],
       [-0.99436786, -0.90191165, -1.01659603, -0.89875651],
       [-0.97602515, -0.94653749, -0.80084579, -1.0364692 ],
       [ 1.61029669,  1.44838243,  1.47020943,  1.82795478],
       [-1.12276681, -1.05066444, -0.97117493, -1.06401174],
       [-0.1872887 , -0.09864659, -0.47154278, -0.54070351],
       [-0.64585641, -0.82753526, -0.51696388, -0.56824605],
       [ 1.02333003,  0.82362071,  0.66398483,  1.69024209],
       [ 0.83990295,  1.6120105 ,  1.28852501,  0.72625325],
       [ 1.4085269 ,  0.88312183,  0.64127427,  1.24956147],
       [-0.73756995, -0.94653749, -0.83491161, -0.92629905],
       [ 0.76653212,  0.49636457,  0.9138009 ,  1.16693386],
       [-0.95768244, -0.

In [58]:
info_matrix = np.concatenate((tfidf_pca, grammar_matrix), axis=1)
print np.shape(info_matrix)

(19, 8)


In [59]:
cosine_similarities = cosine_similarity(info_matrix)
cosine_similarities

array([[ 1.        , -0.61414464,  0.60885981, -0.64773863,  0.630728  ,
        -0.65642424, -0.60385615,  0.53286673, -0.55360107, -0.61103432,
        -0.50649698,  0.40371668,  0.59320193,  0.46056173, -0.63213488,
         0.61381644, -0.53628143,  0.41161593, -0.55332443],
       [-0.61414464,  1.        , -0.95233918,  0.99077288, -0.90577481,
         0.97061887,  0.89064169, -0.95267643,  0.94354093,  0.72506828,
         0.9320621 , -0.89993323, -0.91673817, -0.91058467,  0.94691413,
        -0.94032241,  0.97695626, -0.82194596,  0.98251295],
       [ 0.60885981, -0.95233918,  1.        , -0.96204836,  0.87185969,
        -0.9354192 , -0.84699642,  0.86531295, -0.86574448, -0.59282946,
        -0.91402784,  0.75919048,  0.8923288 ,  0.85236217, -0.86264878,
         0.84991602, -0.91443986,  0.69703503, -0.92026282],
       [-0.64773863,  0.99077288, -0.96204836,  1.        , -0.94088827,
         0.98464548,  0.91639239, -0.9575806 ,  0.93316978,  0.68677868,
         0.959